# SPDX-FileCopyrightText: 2026 The midgard contributors.
# SPDX-License-Identifier: MPL-2.0

name: Security

on:
    push:
        branches:
          - master
    pull_request:
        branches:
          - master

# Declare default permissions as read-only.
permissions: read-all

jobs:
    TrivyCode:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
            with:
                egress-policy: audit

          - name: Checkout code
            uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

          - name: Run Trivy vulnerability scanner in fs mode
            uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # 0.36.0
            with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'sarif'
                output: 'trivy-results.sarif'
                severity: 'CRITICAL,HIGH'

          - name: Upload Trivy scan results to GitHub Security tab
            uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
            with:
                sarif_file: 'trivy-results.sarif'

    VulnerabilityCheck:
        strategy:
            matrix:
                go-version:
                  - "stable"
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
            with:
                egress-policy: audit

          - name: Vulnerability Check
            uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
            with:
                go-version-input: ${{matrix.go-version}}
                output-format: sarif
                output-file: govulncheck-results.sarif

          - name: Print Sarif
            id: printSarif
            run: |
                cat govulncheck-results.sarif

                if grep results govulncheck-results.sarif
                then
                    echo "hasResults=true" >> $GITHUB_OUTPUT
                else
                    echo "hasResults=false" >> $GITHUB_OUTPUT
                fi

          - name: Upload govulncheck results to Security tab
            if: ${{ steps.printSarif.outputs.hasResults == 'true' }}
            uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
            with:
                sarif_file: govulncheck-results.sarif
