# SPDX-FileCopyrightText: 2026 The midgard contributors.
# SPDX-License-Identifier: MPL-2.0

name: Tests

on:
    push:
        branches:
          - master
    pull_request:
        branches:
          - master

# Declare default permissions as read-only.
permissions: read-all

jobs:
    Test:
        strategy:
            matrix:
                go-version:
                  - "stable"
                platform:
                  #- macos-latest
                  - ubuntu-latest
                  #- windows-latest
        runs-on: ${{matrix.platform}}
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
            with:
                egress-policy: audit

          - name: Install Go
            uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
            with:
                go-version: ${{matrix.go-version}}

          - name: Checkout
            uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            with:
                fetch-depth: 1

          - name: Test
            run: go tool gotestsum --junitfile junit.xml -- -race -v `go list ./...` --covermode=atomic --coverpkg=./... --coverprofile=coverage.txt

          - name: Upload test results to Codecov
            if: ${{ !cancelled() }}
            uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
            with:
                report_type: test_results
                token: ${{ secrets.CODECOV_TOKEN }}

          - name: Coverage
            run: go tool cover -func=coverage.txt

          - name: Upload coverage to Codecov
            uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
            with:
                report_type: coverage
                token: ${{ secrets.CODECOV_TOKEN }}

    # This action is mainly composed of snippets of github.com/jidicula/go-fuzz-action
    FuzzTest:
        strategy:
            matrix:
                go-version:
                  - "stable"
                platform:
                  #- macos-latest
                  - ubuntu-latest
                  #- windows-latest
                packages:
                  - ./handler/methodfilter
        runs-on: ${{ matrix.platform }}
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
            with:
                egress-policy: audit

          - name: Install Go
            uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
            with:
                go-version: ${{matrix.go-version}}

          - name: Checkout
            uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            with:
                fetch-depth: 1

          - name: Run Fuzz Test
            shell: bash
            run: go test ${{ matrix.packages }} -fuzz="Fuzz" -fuzztime="30s" -fuzzminimizetime="10s"

          - name: Upload fuzz failure seed corpus as run artifact
            if: failure()
            uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
            with:
                name: testdata
                path: testdata

          - run: echo "EVENT NAME IS ${{ github.event_name }}"
            if: failure()
            shell: bash

          - name: Save PR head commit SHA
            if: failure() && github.event_name == 'pull_request'
            shell: bash
            run: |
                SHA="${{ github.event.pull_request.head.sha }}"
                echo "SHA=$SHA" >> $GITHUB_ENV

          - name: Save latest commit SHA if not PR
            if: failure() && github.event_name != 'pull_request'
            shell: bash
            run: echo "SHA=${{ github.sha }}" >> $GITHUB_ENV

          - name: Output message
            if: failure()
            shell: bash
            run: |
                MESSAGE='Fuzz test failed on commit ${{ env.SHA }}. To troubleshoot locally, use the [GitHub CLI](https://cli.github.com) to download the seed corpus with\n```\ngh run download ${{ github.run_id }} -n testdata\n```'
                DEEPLINK="https://github.com/${{ github.repository }}/commit/${{ env.SHA }}"
                echo -e "${MESSAGE/${{ env.SHA }}/$DEEPLINK}"
                echo -e "${MESSAGE/${{ env.SHA }}/[${GITHUB_SHA:0:8}]($DEEPLINK)}" >> $GITHUB_STEP_SUMMARY
